apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "producer"
    spec:
      containers:
      - name: node
        image: tiagorcdocker/dapr-demo-producer-py
        imagePullPolicy: Always
        env:
        - name: TOPIC
          value: "request-topic"
        - name: PUBSUB
          value: "request-pubsub"