apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  selector:
    app: ingestion
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ingestion"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: ingestion
        image: tiagorcdocker/dapr-demo-ingestion-py
        ports:
        - containerPort: 8080
        imagePullPolicy: Always